services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phantom_mask_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  
  app:
    build: .
    container_name: phantom_web
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  db_data: